insert into users (username, password, firstname, lastname, email) values ('ADMIN', 'ADMIN', 'F_ADMIN', 'L_ADMIN','admin@admin.com');
insert into users (username, password, firstname, lastname, email) values ('Maria', 'Ioana', 'Maria', 'Ioana','m@a.com');
insert into users (username, password, firstname, lastname, email) values ('Buci', 'buci', 'Buci', 'McCuci','buca@a.com');
insert into users (username, password, firstname, lastname, email) values ('Muci', 'muci', 'Muci', 'McFuci','muca@a.com');
insert into users (username, password, firstname, lastname, email) values ('Long69', 'dada69', 'Long', 'Hoang','long@hoang.com');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(101,1,'YES');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(102,1,'YES');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(103,1,'YES');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(104,1,'YES');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(105,1,'YES');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(106,1,'YES');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(107,1,'NO');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(108,1,'NO');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(109,1,'YES');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(110,1,'NO');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(112,1,'YES');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(201,2,'YES');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(202,2,'NO');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(203,2,'NO');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(204,2,'NO');
insert into rooms (roomNumber, roomFloor, canBeReserved) values(205,2,'YES');
insert into reservations(user_id, room_id, start_reservation, end_reservation) values(2,3,CURTIME(), CURTIME());